---
apiVersion: batch/v1
kind: Job
metadata:
  name: test-echo-job
spec:
  # Number of times the pod is restarted on failure.
  backoffLimit: 5
  activeDeadlineSeconds: 300
  template:
    spec:
      containers:
      - name: echo-test
        image: busybox
        command: ["sh", "-c", "sleep 240"]
      restartPolicy: OnFailure
      serviceAccountName: backup-job-serviceaccount
