---
# tasks file for backup
- name: Debug
  debug:
    msg: 'take_final_backup value is: {{ take_final_backup }}'
- name: Pause for 5 seconds
  pause:
    seconds: 5
- name: Take a final db backup
  when:
    - take_final_backup is defined
    - take_final_backup is true
  community.kubernetes.k8s:
    # wait: yes
    # wait_condition:
    #   reason: Started
    #   type: Normal
    # wait_timeout: 240
    definition:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: "{{ backup_job_name }}"
        namespace: "{{ backup_job_namespace }}"
      spec:
        # Number of times the pod is restarted on failure.
        backoffLimit: "{{ backup_job_backoffLimit }}"
        activeDeadlineSeconds: "{{ backup_job_activeDeadlineSeconds }}"
        template:
          spec:
            # Don't restart container, only the whole pod.
            restartPolicy: "{{ backup_job_restartPolicy }}"
            containers:
              - name: echo-test
                image: busybox
                command: ["sh", "-c", "sleep 240"]
            #serviceAccountName: backup-job-serviceaccount
            # containers:
            #   - name: db-backup-job
            #     image: ozziio/mysql-backup-s3:latest
            #     imagePullPolicy: IfNotPresent
            #     env:
            #       - name: S3_ACCESS_KEY_ID
            #         valueFrom:
            #           secretKeyRef:
            #             name: "auto-db-backup-secret"
            #             key: aws_access_key
            #       - name: S3_SECRET_ACCESS_KEY
            #         valueFrom:
            #           secretKeyRef:
            #             name: "auto-db-backup-secret"
            #             key: aws_secret_access_key
            #       - name: S3_REGION
            #         valueFrom:
            #           secretKeyRef:
            #             name: "auto-db-backup-secret"
            #             key: region
            #             optional: true
            #       - name: S3_BUCKET
            #         valueFrom:
            #           secretKeyRef:
            #             name: "auto-db-backup-secret"
            #             key: bucket
            #       - name: S3_ENDPOINT
            #         optional: 1
            #         valueFrom:
            #           secretKeyRef:
            #             name: "auto-db-backup-secret"
            #             key: endpoint
            #             optional: true
            #       - name: DEBUG
            #         valueFrom:
            #           secretKeyRef:
            #             name: "auto-db-backup-secret"
            #             key: debug
            #             optional: true
            #       - name: S3_PREFIX
            #         value: "{{ ansible_operator_meta.name }}"
            #       - name: MYSQL_HOST
            #         value: "{{ ansible_operator_meta.name }}-db"
            #       - name: MYSQL_PORT
            #         value: "3306"
            #       - name: MYSQLDUMP_DATABASE
            #         valueFrom:
            #           secretKeyRef:
            #             name: "{{ ansible_operator_meta.name }}.drupal-secrets"
            #             key: db_database
            #       - name: MYSQL_USER
            #         valueFrom:
            #           secretKeyRef:
            #             name: "{{ ansible_operator_meta.name }}.drupal-secrets"
            #             key: db_user
            #       - name: MYSQL_PASSWORD
            #         valueFrom:
            #           secretKeyRef:
            #             name: "{{ ansible_operator_meta.name }}.drupal-secrets"
            #             key: db_password