# permissions for end users to edit drupals.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: drupal-editor-role
rules:
- apiGroups:
  - ozzi.io
  resources:
  - drupals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ozzi.io
  resources:
  - drupals/status
  verbs:
  - get
