---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
        # Custom permissions
      - configmaps
      - persistentvolumeclaims
      - services
      - persistentvolumes
      - events
      - secrets
      - cronjobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for ozzi.io/v1alpha2, Kind: Drupal
  ##
  - apiGroups:
      - ozzi.io
    resources:
      - drupals
      - drupals/status
 #     - drupals/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - batch
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    resources:
      - cronjobs
      - jobs

# +kubebuilder:scaffold:rules
