---
- import_playbook: ../default/prepare.yml

- name: Prepare operator resources
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    deploy_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"
  tasks:
  - name: Create Custom Resource Definition
    community.kubernetes.k8s:
      definition: "{{ lookup('file', '/'.join([deploy_dir, 'crds/drupal_v1alpha2_drupal_crd.yaml'])) }}"

  - name: Ensure specified namespace is present
    community.kubernetes.k8s:
      api_version: v1
      kind: Namespace
      name: '{{ operator_namespace }}'

  - name: Create RBAC resources
    community.kubernetes.k8s:
      definition: "{{ lookup('template', '/'.join([deploy_dir, item])) }}"
      namespace: '{{ operator_namespace }}'
    with_items:
      - role.yaml
      - role_binding.yaml
      - service_account.yaml
