apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: drupal-operator
rules:
- apiGroups:
  - ""
  - extensions
  - apps
  - batch
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - persistentvolumes
  - events
  - configmaps
  - secrets
  - cronjobs
  verbs:
  - '*'
- apiGroups:
  - ""
  - extensions
  - apps
  - batch
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  - extensions
  - apps
  - batch
  resources:
  - pods
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - ozzi.io
  resources:
  - '*'
  verbs:
  - '*'
