---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: manager
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.3"
            limits:
              memory: "256Mi"
              cpu: "1"
