apiVersion: drupal.org/v1alpha2
kind: Drupal
metadata:
  name: example1-drupal
spec:
  tag: 8.7-apache # docker tag
  drupal_image:  drupal:{{ tag }} # docker image - you could also set both tag and image here
  type: production
  db_pvc: microk8s-hostpath
  files_pvc: microk8s-hostpath
  db_pvc_size: 2Gi
  files_pvc_size: 1Gi
  files_accessmode: ReadWriteOnce
  drupal_replicas: 1
  drupal_extra_config: |
    $conf['bar'] = 'foo';
    $conf['foo'] = 'bar';
