---
  - name: Drupal Settings
    k8s:
      definition:
        kind: ConfigMap
        apiVersion: v1
        metadata:
          name: '{{ meta.name }}-drupal-config'
          namespace: '{{ meta.namespace }}'
          labels:
            app: drupal
            site: '{{ meta.name }}'
            drupal: '{{ meta.name }}'
        data:
          settings.php: '{{ drupal_settings_php }}'


# Could be useful later
  - name: Shared config
    k8s:
      definition:
        kind: ConfigMap
        apiVersion: v1
        metadata:
          name: '{{ meta.name }}-shared-config'
          namespace: '{{ meta.namespace }}'
          labels:
            app: drupal
            site: '{{ meta.name }}'
            drupal: '{{ meta.name }}'
        data:
          meta-name: '{{ meta.name }}'
          meta-namespace: '{{ meta.namespace }}'
          db-host: '{{ meta.name }}-db'

  - name: Files PVC
    k8s:
      definition:
        kind: PersistentVolumeClaim
        apiVersion: v1
        metadata:
          name: '{{ meta.name }}-files-pvc'
          namespace: '{{ meta.namespace }}'
          labels:
            app: drupal
            site: '{{ meta.name }}'
            drupal: '{{ meta.name }}'
        spec:
          storageClassName: '{{ files_pvc | default("default") }}'
          accessModes:
            - '{{ files_accessmode | default("ReadWriteOnce")}}'
          resources:
            requests:
              storage: '{{ files_pvc_size  | default("1Gi") }}'

  - name: Mariadb PVC
    k8s:
      definition:
        kind: PersistentVolumeClaim
        apiVersion: v1
        metadata:
          name: '{{ meta.name }}-db-pvc'
          namespace: '{{ meta.namespace }}'
          labels:
            app: mariadb
            site: '{{ meta.name }}'
            db: '{{ meta.name }}'
        spec:
          storageClassName: '{{ db_pvc | default("default") }}'
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: '{{ db_pvc_size  | default("2Gi") }}'

  - name: Drupal
    k8s:
      definition:
        kind: Deployment
        apiVersion: apps/v1
        metadata:
          name: '{{ meta.name }}-drupal'
          namespace: '{{ meta.namespace }}'
        spec:
          replicas: '{{ drupal_replicas }}'
          strategy:
          rollingUpdate:
            maxSurge: 0
            maxUnavailable: 1
          type: RollingUpdate
          selector:
            matchLabels:
              drupal: '{{ meta.name }}'
          template:
            metadata:
              labels:
                drupal: '{{ meta.name }}'
                app: drupal
                site: '{{ meta.name }}'
            spec:
              initContainers:
              - name: init-db
                image: busybox:1.28
                command: ['sh', '-c', "until nslookup '{{ meta.name }}-db'; do echo waiting for '{{ meta.name }}-db'; sleep 2; done;"]
              - name: init-drupal
                imagePullPolicy: Always
                image: '{{ drupal_image | default("drupal:8.7-apache")}}'
                command: [ 'bash' , '-c' , "until ls /var/www/html/sites/default/files/; do echo waiting for volume; sleep 2; done; chown www-data:www-data -R /var/www/html/sites/default/files && chmod -R 755 /var/www/html/sites/default/files" ]
                volumeMounts:
                - mountPath: /var/www/html/sites/default/settings.php
                  subPath: settings.php
                  name: drupal-settings
                - mountPath: /var/www/html/sites/default/files/
                  name: drupal-files
                imagePullSecrets:
                - name:  '{{ drupal_image_reg_secret }}'
                volumes:
                - name: drupal-files
                  persistentVolumeClaim:
                    claimName: '{{ meta.name }}-files-pvc'
              containers:
              - name: drupal
                imagePullPolicy: Always
                image: '{{ drupal_image | default("drupal:8.7-apache")}}'
                ports:
                  - containerPort: 80
                livenessProbe:
                  tcpSocket:
                    port: 80
                  initialDelaySeconds: 60
                readinessProbe:
                  tcpSocket:
                    port: 80
                  initialDelaySeconds: 30
                volumeMounts:
                - mountPath: /var/www/html/sites/default/settings.php
                  subPath: settings.php
                  name: drupal-settings
                - mountPath: /var/www/html/sites/default/files/
                  name: drupal-files
              imagePullSecrets:
                - name:  '{{ drupal_image_reg_secret }}'
              volumes:
              - name: drupal-settings
                configMap:
                  name: '{{ meta.name }}-drupal-config'
              - name: drupal-files
                persistentVolumeClaim:
                  claimName: '{{ meta.name }}-files-pvc'

  - name: Drupal secrets
    k8s:
      definition:
        apiVersion: v1
        kind: Secret
        metadata:
          name: '{{ meta.name }}.drupal-secrets'
          namespace: '{{ meta.namespace }}'
          labels:
            app: drupal
            site: '{{ meta.name }}'
            drupal: '{{ meta.name }}'
        type: Opaque
        data:
          db_database: '{{ drupal_db | b64encode }}'
          db_password: '{{ drupal_db_pass | b64encode }}'
          db_user: '{{ drupal_db_username | b64encode }}'
          password: '{{ drupal_password | b64encode }}'
          user: '{{ drupal_user | b64encode }}'

  - name: Mariadb secrets
    k8s:
      definition:
        apiVersion: v1
        kind: Secret
        metadata:
          name: '{{ meta.name }}.mariadb-secrets'
          namespace: '{{ meta.namespace }}'
          labels:
            app: mariadb
            site: '{{ meta.name }}'
            db: '{{ meta.name }}'
        type: Opaque
        data:
          root_password: '{{ mysql_root_password | b64encode }}'
  - name: Mariadb
    k8s:
      definition:
        kind: StatefulSet
        apiVersion: apps/v1
        metadata:
          name: '{{ meta.name }}-db'
          namespace: '{{ meta.namespace }}'
        spec:
          replicas: 1
          selector:
            matchLabels:
              db: '{{ meta.name }}'
          strategy:
            type: Recreate
          template:
            metadata:
              labels:
                app: mariadb
                site: '{{ meta.name }}'
                db: '{{ meta.name }}'
            spec:
              containers:
              - name: mariadb
                image: "mariadb:10"
                ports:
                  - containerPort: 3306
                env:
                  - name: MYSQL_DATABASE
                    valueFrom:
                      secretKeyRef:
                        name: '{{ meta.name }}.drupal-secrets'
                        key: db_database
                  - name: MYSQL_USER
                    valueFrom:
                      secretKeyRef:
                        name: '{{ meta.name }}.drupal-secrets'
                        key: db_user
                  - name: MYSQL_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: '{{ meta.name }}.drupal-secrets'
                        key: db_password
                  - name: MYSQL_ROOT_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: '{{ meta.name }}.mariadb-secrets'
                        key: root_password
                volumeMounts:
                - mountPath: /var/lib/mysql/
                  name: drupal-db
              volumes:
                - name: drupal-db
                  persistentVolumeClaim:
                    claimName: '{{ meta.name }}-db-pvc'

  - name: Mariadb Service
    k8s:
      definition:
        kind: Service
        apiVersion: v1
        metadata:
          name: '{{ meta.name }}-db'
          namespace: '{{ meta.namespace }}'
          labels:
            app: mariadb
            site: '{{ meta.name }}'
        spec:
          type: NodePort
          ports:
            - port: 3306
              targetPort: 3306
          selector:
            db: '{{ meta.name }}'

  - name: Drupal Service
    k8s:
      definition:
        kind: Service
        apiVersion: v1
        metadata:
          name: '{{ meta.name }}-service'
          namespace: '{{ meta.namespace }}'
          labels:
            app: drupal
            site: '{{ meta.name }}'
        spec:
          type: NodePort
          ports:
            - port: 80
              targetPort: 80
          selector:
            drupal: '{{ meta.name }}'
