---
- name: Drupal Settings
  k8s:
    state: present
    definition:
        kind: ConfigMap
        apiVersion: v1
        metadata:
          name: '{{ meta.name }}-drupal-config'
          namespace: '{{ meta.namespace }}'
          labels:
            app: drupal
            site: '{{ meta.name }}'
            drupal: '{{ meta.name }}'
        data:
          settings.php: '{{ drupal_settings_php }}'

- name: Drupal startup
  k8s:
    definition:
        kind: ConfigMap
        apiVersion: v1
        metadata:
          name: '{{ meta.name }}-drupal-startup'
          namespace: '{{ meta.namespace }}'
          labels:
            app: drupal
            site: '{{ meta.name }}'
            drupal: '{{ meta.name }}'
        data:
          startup.sh: '{{ drupal_startup }}'

- name: Files PVC
  k8s:
    definition:
      kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: '{{ meta.name }}-files-pvc'
        namespace: '{{ meta.namespace }}'
        labels:
          app: drupal
          site: '{{ meta.name }}'
          drupal: '{{ meta.name }}'
      spec:
        storageClassName: '{{ files_pvc }}'
        accessModes:
          - '{{ files_accessmode }}'
        resources:
          requests:
            storage: '{{ files_pvc_size }}'

- name: Mariadb PVC
  when: no_db is not defined
  k8s:
    definition:
      kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: '{{ meta.name }}-db-pvc'
        namespace: '{{ meta.namespace }}'
        labels:
          app: mariadb
          site: '{{ meta.name }}'
          db: '{{ meta.name }}'
      spec:
        storageClassName: '{{ db_pvc }}'
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: '{{ db_pvc_size }}'

- name: Drupal
  k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: '{{ meta.name }}-drupal'
        namespace: '{{ meta.namespace }}'
      spec:
        replicas: '{{ drupal_replicas }}'
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 25%
        selector:
          matchLabels:
            drupal: '{{ meta.name }}'
        template:
          metadata:
            labels:
              drupal: '{{ meta.name }}'
              app: drupal
              site: '{{ meta.name }}'
            annotations:
              kubernetes.io/change-cause: '{{ change_cause }}'
          spec:
            initContainers:
            - name: init-db
              when: no_db is not defined
              image: busybox:1.28
              command: ['sh', '-c', "until nslookup '{{ meta.name }}-db'; do echo waiting for '{{ meta.name }}-db'; sleep 2; done;"]
            - name: init-drupal
              image: '{{ drupal_image }}'
              env:
                - name: DRUPAL_LOCALE
                  value: '{{ drupal_locale }}'
                - name: DRUPAL_LOCALE
                  value: '{{ drupal_locale }}'  
                - name: MYSQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: '{{ meta.name }}.drupal-secrets'
                      key: db_database
                - name: MYSQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: '{{ meta.name }}.drupal-secrets'
                      key: db_user
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: '{{ meta.name }}.drupal-secrets'
                      key: db_password
                - name: DRUPAL_USER
                  valueFrom:
                    secretKeyRef:
                      name: '{{ meta.name }}.drupal-secrets'
                      key: user
                - name: DRUPAL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: '{{ meta.name }}.drupal-secrets'
                      key: password  
              command: 
              - /bin/sh 
              - -c
              - while [ ! -f /scripts/settings.php ]; do echo waiting; sleep 2; done;
                cp /scripts/settings.php /pre-scripts/settings.php;
                cp /scripts/startup.sh /pre-scripts/startup.sh;
                chown -R www-data:www-data -R /pre-scripts;
                cp /pre-scripts/settings.php {{ drupal_web_root }}/sites/default/settings.php;
                cp /pre-scripts/startup.sh {{ drupal_root }}/startup.sh; 
                chmod 777 {{ drupal_root }}/startup.sh; 
                chown -R www-data:www-data {{ drupal_web_root }};
                {{ drupal_root }}/startup.sh
              volumeMounts:
              - mountPath: '/scripts/startup.sh'
                subPath: startup.sh
                name: drupal-startup
              - mountPath: '/scripts/settings.php'
                subPath: settings.php
                name: drupal-settings
              - name: pre-scripts
                mountPath: /pre-scripts
              - mountPath: '{{ drupal_web_root }}/sites/default/files/'
                name: drupal-files  
            containers:    
            - name: '{{ drupal_name }}'
              lifecycle:
                postStart:
                  exec:
                    command: 
                    - /bin/sh
                    - -c 
                    - while [ ! -f /pre-scripts/settings.php ]; do echo waiting; sleep 2; done && cp /pre-scripts/settings.php {{ drupal_web_root }}/sites/default/settings.php;
              imagePullPolicy: '{{ drupal_image_pull_policy }}'
              image: '{{ drupal_image }}'
              resources:
                requests:
                  memory: '{{ drupal_resources_requests_memory }}'
                  cpu: '{{ drupal_resources_requests_cpu }}'
                limits:
                  memory: '{{ drupal_resources_limits_memory }}'
                  cpu: '{{ drupal_resources_limits_cpu }}'
              ports:
                - containerPort: '{{ drupal_ports_containerPort }}'
              livenessProbe:
                tcpSocket:
                  port: '{{ drupal_livenessProbe_tcpSocket_port }}'
                initialDelaySeconds: '{{ drupal_livenessProbe_initialDelaySeconds }}'
                periodSeconds: '{{ drupal_livenessProbe_periodSeconds }}'
                timeoutSeconds: '{{ drupal_livenessProbe_timeoutSeconds }}'
              env:
                - name: DRUPAL_LOCALE
                  value: '{{ drupal_locale }}'
                - name: MYSQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: '{{ meta.name }}.drupal-secrets'
                      key: db_database
                - name: MYSQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: '{{ meta.name }}.drupal-secrets'
                      key: db_user
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: '{{ meta.name }}.drupal-secrets'
                      key: db_password
                - name: DRUPAL_USER
                  valueFrom:
                    secretKeyRef:
                      name: '{{ meta.name }}.drupal-secrets'
                      key: user
                - name: DRUPAL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: '{{ meta.name }}.drupal-secrets'
                      key: password                      
              volumeMounts:
              - mountPath: '{{ drupal_web_root }}/sites/default/files/'
                name: drupal-files
              - mountPath: /pre-scripts
                name: pre-scripts
            imagePullSecrets:
              - name:  '{{ drupal_image_reg_secret }}'
            volumes:
            - name: drupal-settings
              configMap:
                name: '{{ meta.name }}-drupal-config'
            - name: drupal-startup
              configMap:
                name: '{{ meta.name }}-drupal-startup'
            - name: pre-scripts
              emptyDir: {}
            - name: drupal-files
              persistentVolumeClaim:
                claimName: '{{ meta.name }}-files-pvc'

- name: Drupal secrets
  k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: '{{ meta.name }}.drupal-secrets'
        namespace: '{{ meta.namespace }}'
        labels:
          app: drupal
          site: '{{ meta.name }}'
          drupal: '{{ meta.name }}'
      type: Opaque
      data:
        db_database: '{{ drupal_db | b64encode }}'
        db_password: '{{ drupal_db_pass | b64encode }}'
        db_user: '{{ drupal_db_username | b64encode }}'
        password: '{{ drupal_password | b64encode }}'
        user: '{{ drupal_user | b64encode }}'

- name: Mariadb secrets
  when: no_db is not defined
  k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: '{{ meta.name }}.mariadb-secrets'
        namespace: '{{ meta.namespace }}'
        labels:
          app: mariadb
          site: '{{ meta.name }}'
          db: '{{ meta.name }}'
      type: Opaque
      data:
        root_password: '{{ mysql_root_password | b64encode }}'

- name: Mariadb
  when: no_db is not defined
  k8s:
    definition:
      kind: StatefulSet
      apiVersion: apps/v1
      metadata:
        name: '{{ meta.name }}-db'
        namespace: '{{ meta.namespace }}'
      spec:
        replicas: 1
        selector:
          matchLabels:
            db: '{{ meta.name }}'
        strategy:
          type: Recreate
        template:
          metadata:
            labels:
              app: mariadb
              site: '{{ meta.name }}'
              db: '{{ meta.name }}'
          spec:
            containers:
            - name: mariadb
              image: "mariadb:10"
              ports:
                - containerPort: 3306
              env:
                - name: MYSQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: '{{ meta.name }}.drupal-secrets'
                      key: db_database
                - name: MYSQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: '{{ meta.name }}.drupal-secrets'
                      key: db_user
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: '{{ meta.name }}.drupal-secrets'
                      key: db_password
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: '{{ meta.name }}.mariadb-secrets'
                      key: root_password
              volumeMounts:
              - mountPath: /var/lib/mysql/
                name: drupal-db
            volumes:
              - name: drupal-db
                persistentVolumeClaim:
                  claimName: '{{ meta.name }}-db-pvc'

- name: Mariadb Nodeport
  when: no_db is not defined
  k8s:
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: '{{ meta.name }}-db'
        namespace: '{{ meta.namespace }}'
        labels:
          app: mariadb
          site: '{{ meta.name }}'
      spec:
        type: NodePort
        ports:
          - port: 3306
            targetPort: 3306
        selector:
          db: '{{ meta.name }}'

- name: Drupal Nodeport
  when: 
    - no_drupal_nodeport is not defined
  k8s:
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: '{{ meta.name }}-np'
        namespace: '{{ meta.namespace }}'
        labels:
          app: drupal
          site: '{{ meta.name }}'
      spec:
        type: NodePort
        ports:
          - port: 80
            targetPort: 80
        selector:
          drupal: '{{ meta.name }}'

- name: Drupal Loadbalancer
  when: 
    - drupal_loadbalancer
  k8s:
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: '{{ meta.name }}-lb'
        namespace: '{{ meta.namespace }}'
        labels:
          app: drupal
          site: '{{ meta.name }}'
      spec:
        type: LoadBalancer
        ports:
          - port: 80
            targetPort: 80
        selector:
          drupal: '{{ meta.name }}'

# - name: Drupal cron
#   when:
#     - drupal_cron is defined
#     - drupal_cron
#   k8s_raw:
#     definition:
#       kind: CronJob
#       apiVersion: batch/v1beta1
#       metadata:
#         name: '{{ meta.name }}-drupal-cron'
#         namespace: '{{ meta.namespace }}'
#       spec:
#         schedule: '{{ drupal_cron_schedule }}'
#         concurrencyPolicy: '{{ drupal_cron_concurrencyPolicy }}'
#         successfulJobsHistoryLimit: '{{ drupal_cron_successfulJobsHistoryLimit }}'
#         failedJobsHistoryLimit: '{{ drupal_cron_failedJobsHistoryLimit }}'
#         jobTemplate:
#           spec:
#             activeDeadlineSeconds: '{{ drupal_cron_activeDeadlineSeconds }}'
#             template:
#               spec:
#                 restartPolicy: '{{ drupal_cron_restartPolicy }}'
#                 containers:
#                 - name: drupal-cron
#                   args:
#                   - '{{ drupal_cron_shell }}'
#                   - -c
#                   - '{{ drupal_cron_args }}'
#                   imagePullPolicy: '{{ drupal_image_pull_policy }}'
#                   image: '{{ drupal_image }}'
#                   ports:
#                     - containerPort: 80
#                   livenessProbe:
#                     tcpSocket:
#                       port: 80
#                     initialDelaySeconds: 5
#                   readinessProbe:
#                     tcpSocket:
#                       port: 80
#                     initialDelaySeconds: 5
#                   volumeMounts:
#                   - mountPath: '{{ drupal_web_root }}/sites/default/settings.php'
#                     subPath: settings.php
#                     name: drupal-settings
#                   - mountPath: '{{ drupal_web_root }}/sites/default/files/'
#                     name: drupal-files
#                 imagePullSecrets:
#                   - name:  '{{ drupal_image_reg_secret }}'
#                 volumes:
#                 - name: drupal-settings
#                   configMap:
#                     name: '{{ meta.name }}-drupal-config'
#                 - name: drupal-files
#                   persistentVolumeClaim:
#                     claimName: '{{ meta.name }}-files-pvc'

# - name: automatic db backup secret
#   when:
#     - auto_backup is defined
#     - auto_backup
#   k8s_raw:
#     definition:
#       apiVersion: v1
#       kind: Secret
#       metadata:
#         name: '{{ meta.name }}-auto-db-backup-secret'
#         namespace: '{{ meta.namespace }}'
#       type: Opaque
#       data:
#         aws_access_key: '{{ aws_access_key | b64encode }}'
#         aws_secret_access_key: '{{ aws_secret_access_key | b64encode }}'
#         backup_endpoint: '{{ backup_endpoint | b64encode }}'

- name: automatic db backup
  when:
    - auto_backup is defined
  k8s:
    definition:
      apiVersion: batch/v1beta1
      kind: CronJob
      metadata:
        name: '{{ meta.name }}-auto-db-backup'
        namespace: '{{ meta.namespace }}'
      spec:
        schedule: '{{ backup_cron_schedule }}'
        jobTemplate:
          spec:
            template:
              spec:
                containers:
                - name: auto-db-backup
                  image: ozziio/mysql-backup-s3
                  imagePullPolicy: IfNotPresent
                  env:
                    - name: S3_ACCESS_KEY_ID
                      valueFrom:
                        secretKeyRef:
                          name: 'auto-db-backup-secret'
                          key: aws_access_key
                    - name: S3_SECRET_ACCESS_KEY
                      valueFrom:
                        secretKeyRef:
                          name: 'auto-db-backup-secret'
                          key: aws_secret_access_key
                    - name: S3_REGION
                      valueFrom:
                        secretKeyRef:
                          name: 'auto-db-backup-secret'
                          key: region
                          optional: true
                    - name: S3_BUCKET
                      valueFrom:
                        secretKeyRef:
                          name: 'auto-db-backup-secret'
                          key: bucket                       
                    - name: S3_ENDPOINT
                      optional: 1
                      valueFrom:
                        secretKeyRef:
                          name: 'auto-db-backup-secret'
                          key: endpoint
                          optional: true
                    - name: DEBUG
                      valueFrom:
                        secretKeyRef:
                          name: 'auto-db-backup-secret'
                          key: debug
                          optional: true      
                    - name: S3_PREFIX
                      value: '{{ meta.name }}'
                    - name: MYSQL_HOST
                      value: '{{ meta.name }}-db'
                    - name: MYSQL_PORT
                      value: "3306"
                    - name: MYSQLDUMP_DATABASE
                      valueFrom:
                        secretKeyRef:
                          name: '{{ meta.name }}.drupal-secrets'
                          key: db_database
                    - name: MYSQL_USER
                      valueFrom:
                        secretKeyRef:
                          name: '{{ meta.name }}.drupal-secrets'
                          key: db_user
                    - name: MYSQL_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: '{{ meta.name }}.drupal-secrets'
                          key: db_password
                restartPolicy: Never

- name: Drupal Ingress
  when: 
    - drupal_loadbalancer
  k8s:
    definition:
      apiVersion: extensions/v1beta1
      kind: Ingress
      metadata:
        name: '{{ meta.name }}'
        namespace: '{{ meta.namespace }}'
        annotations:
          nginx.org/proxy-connect-timeout: "30s"
          nginx.org/proxy-read-timeout: "20s"
          nginx.org/client-max-body-size: "20m"
          nnginx.org/proxy-hide-headers: "X-Powered-By, X-Generator"
      spec:
        rules:
          - host: '{{ drupal_hostname }}'
        backend:
          serviceName: '{{ meta.name }}-lb'
          servicePort: 80