---
# defaults file for backup
backup_job_name: "{{ ansible_operator_meta.name }}-final-db-backup"
backup_job_namespace: "{{ ansible_operator_meta.namespace }}"
# Try N times on failure
backup_job_backoffLimit: 5
# Can be Never or OnFailure. OnFailure only restarts the container, not the whole pod.
backup_job_restartPolicy: OnFailure
# Terminate after latest N seconds
backup_job_activeDeadlineSeconds: 300
